ExternalBadass/ExternalBadass/Models/UserActivity.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace ExternalBadass.Models
{
    public class UserActivity
    {
        [Key, Column(Order = 0)]
        public int UserId { get; set; }
        [Key, Column(Order = 1)]
        public int ActivityId { get; set; }
        [Key, Column(Order = 3)]
        public DateTime Date { get; set; }

        public User User { get; set; }
        public Activity Activity { get; set; }
    }
}

ExternalBadass/ExternalBadass/ViewModels/UserActivityViewModel.cs
using ExternalBadass.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ExternalBadass.ViewModels
{
    public class UserActivityViewModel
    {
        public UserActivityViewModel(IEnumerable<User> users, IEnumerable<Activity> activities, User currentUser)
        {
            Users = users;
            Activities = activities;
            CurrentUser = currentUser;
        }

        public IEnumerable<User> Users { get; set; }


        public IEnumerable<Activity> Activities { get; set; }

        public User CurrentUser { get; set; }

        public SelectList UserSelectList {
            get
            {
                return new SelectList(Users, "UserId", "Username", CurrentUser.UserId);
            }
        }
       
        public SelectList ActivitySelectList
        {
            get
            {
                return new SelectList(Activities, "ActivityId", "Name");
            }
        }



    }
}

ExternalBadass/ExternalBadass/Controllers/UserActivityController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ExternalBadass.Models;
using ExternalBadass.ViewModels;
using ExternalBadass.Services;

namespace ExternalBadass.Controllers
{
    public class UserActivityController : Controller
    {
        private BadassContext db = new BadassContext();
        UserActivityService _uaService = null;

        public UserActivityController()
        {
             _uaService = new UserActivityService(db);
        }

        //
        // GET: /UserActivity/vegashat
        public ActionResult Index(string username)
        {
            var activities = GetActivityForUser(username);

            ViewBag.Username = username;

            return View(activities);
        }

        private IEnumerable<UserActivity> GetActivityForUser(string username)
        {
            IEnumerable<UserActivity> activities = null;

            if (db.Users.Any(u => u.Username == username))
            {
                activities = db.UserActivities.Include(ua => ua.User).Include(ua => ua.Activity).Where(ua => ua.User.Username == username);
            }
            return activities;
        }

        public ActionResult Status(string username)
        {
            var incentives = db.Incentives.Include(i => i.User).Where(i => i.User.Username == username);
            var userActivities = db.UserActivities.Include(ua => ua.User).Include(ua => ua.Activity).Where(ua => ua.User.Username == username);
            var users = db.Users;
            var model = new CurrentStatusViewModel(incentives.ToList(), userActivities.ToList(), users.ToList());

            return View(model);
        }

        //
        // GET: /UserActivity/Details/5

        public ActionResult Details(int id = 0)
        {
            UserActivity useractivity = db.UserActivities.Find(id);
            if (useractivity == null)
            {
                return HttpNotFound();
            }
            return View(useractivity);
        }

        //
        // GET: /UserActivity/Create

        public ActionResult Create(string username)
        {

            var users = db.Users;
            var activities = db.Activities;
            var currentUser = users.Include(u => u.Activities).First(u => u.Username == username);

            var model = new UserActivityViewModel(users, activities, currentUser);

            return View(model);
        }

        public ActionResult CreatePartial(string username)
        {            
            var users = db.Users;
            var activities = db.Activities;
            var currentUser = users.Include(u => u.Activities).First(u => u.Username == username);

            var model = new UserActivityViewModel(users, activities, currentUser);

            return PartialView("_Create", model);
        }

        //
        // POST: /UserActivity/Create

        [HttpPost]
        public ActionResult Create(UserActivity userActivity)
        {
            if (ModelState.IsValid)
            {
                userActivity.UserId = userActivity.User.UserId;
                userActivity.ActivityId = userActivity.Activity.ActivityId;

                userActivity.User = db.Users.Find(userActivity.UserId);
                userActivity.Activity = db.Activities.Find(userActivity.ActivityId);

                db.UserActivities.Add(userActivity);
                db.SaveChanges();

                _uaService.CalculateIncentives(userActivity.User.Username);

                return RedirectToAction("Index", new { username = userActivity.User.Username });
                
            }

            return RedirectToAction("Index", new { username = userActivity.User.Username });
        }

        [HttpPost]
        public JsonResult AddActivity(UserActivity userActivity)
        {
            dynamic response = null;

            try
            {
                userActivity.UserId = userActivity.User.UserId;
                userActivity.ActivityId = userActivity.Activity.ActivityId;

                userActivity.User = db.Users.Find(userActivity.UserId);
                userActivity.Activity = db.Activities.Find(userActivity.ActivityId);

                db.UserActivities.Add(userActivity);
                db.SaveChanges();

                _uaService.CalculateIncentives(userActivity.User.Username);

                response = new { Success = true, Title = userActivity.Activity.Name, Date = userActivity.Date.ToShortDateString() };
            }
            catch(Exception ex)
            {
                response = new { Success = false, Message = ex.Message };
            }

            return Json(response);
        }

        //
        // GET: /UserActivity/Edit/5

        public ActionResult Edit(int userId, int activityId, DateTime date)
        {
            UserActivity useractivity = db.UserActivities.FirstOrDefault(ua => ua.UserId == userId && ua.ActivityId == activityId && ua.Date == date);
            if (useractivity == null)
            {
                return HttpNotFound();
            }
            ViewBag.UserId = new SelectList(db.Users, "UserId", "Username", useractivity.UserId);
            ViewBag.ActivityId = new SelectList(db.Activities, "ActivityId", "Name", useractivity.ActivityId);
            return View(useractivity);
        }

        //
        // POST: /UserActivity/Edit/5

        [HttpPost]
        public ActionResult Edit(UserActivity useractivity)
        {
            if (ModelState.IsValid)
            {
                db.Entry(useractivity).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.UserId = new SelectList(db.Users, "UserId", "Username", useractivity.UserId);
            ViewBag.ActivityId = new SelectList(db.Activities, "ActivityId", "Name", useractivity.ActivityId);


            _uaService.CalculateIncentives(useractivity.User.Username);

            return View(useractivity);
        }

        public ActionResult Delete(int userId, int activityId, DateTime date)
        {
            UserActivity useractivity = db.UserActivities.Include(ua => ua.User).FirstOrDefault(ua => ua.UserId == userId && ua.ActivityId == activityId && ua.Date == date);
            var username = useractivity.User.Username;
            
            db.UserActivities.Remove(useractivity); 
            db.SaveChanges();

            _uaService.CalculateIncentives(username);

            return RedirectToAction("Index", new { username = username });
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }

        public JsonResult GetUserActivity(string username)
        {
            var activities = GetActivityForUser(username);

            var calendarValues = from a in activities
                                 select new { title = a.Activity.Name, date=a.Date.ToShortDateString(), start = a.Date.ToShortDateString(), end = a.Date.ToShortDateString(), allDay = true };

            return Json(calendarValues, JsonRequestBehavior.AllowGet);

        }
    }
}

ExternalBadass/ExternalBadass/Views/UserActivity/Create.cshtml
@model ExternalBadass.ViewModels.UserActivityViewModel

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>UserActivity</legend>

            @Html.Hidden("UserActivity.User.Username", Model.CurrentUser.Username)

         <div class="editor-label">
            @Html.LabelFor(model => model.CurrentUser.Username)
        </div>
        <div class="editor-field">
            @Html.DropDownList("UserActivity.User.UserId", Model.UserSelectList)
        </div>
         <div class="editor-label">
            <label for="UserActivity.ActivityId">Date</label>
        </div>
        <div class="editor-field">
            @Html.TextBox("UserActivity.Date", DateTime.Now.ToShortDateString(), new { @class = "datepicker" })
        </div>
         <div class="editor-label">
            <label for="UserActivity.ActivityId">Activity</label>
        </div>
        <div class="editor-field">
            @Html.DropDownList("UserActivity.Activity.ActivityId", Model.ActivitySelectList)
        </div>

        <p>
            <input type="submit" value="Create" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")

}

ExternalBadass/ExternalBadass/Views/UserActivity/Delete.cshtml
@model ExternalBadass.Models.UserActivity

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<fieldset>
    <legend>UserActivity</legend>
</fieldset>
@using (Html.BeginForm()) {
    <p>

        <input type="submit" value="Delete" /> |
        @Html.ActionLink("Back to List", "Index")
    </p>
}

ExternalBadass/ExternalBadass/Views/UserActivity/Details.cshtml
@model ExternalBadass.Models.UserActivity

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<fieldset>
    <legend>UserActivity</legend>
</fieldset>
<p>
    @Html.ActionLink("Edit", "Edit", new { /* id=Model.PrimaryKey */ }) |
    @Html.ActionLink("Back to List", "Index")
</p>

ExternalBadass/ExternalBadass/Views/UserActivity/Edit.cshtml
@model ExternalBadass.Models.UserActivity

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>UserActivity</legend>

        @Html.HiddenFor(model => model.UserId)

        @Html.HiddenFor(model => model.ActivityId)

        <p>
            <input type="submit" value="Save" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ExternalBadass/ExternalBadass/Views/UserActivity/Index.cshtml
@model IEnumerable<ExternalBadass.Models.UserActivity>

@{
    ViewBag.Title = "Current Activity";
}

<ul class="nav nav-tabs">
    <li><a href="#list-view" data-toggle="tab">List View</a></li>
    <li><a href="#calendar-view2" data-toggle="tab">Calendar View</a></li>
</ul>

<div class="tab-content">
    <div class="tab-pane" id="list-view">
        <p>
            @Html.ActionLink("Create New", "Create", new { username = ViewBag.Username })
        </p>
        <table class="table table-striped">
            <tr>
                <th>Activity</th>
                <th>Date</th>
                <th>Points</th>
                <th></th>
            </tr>

            @foreach (var item in Model)
            {
                <tr>
                    <td>@item.Activity.Name</td>
                    <td>@item.Date.ToShortDateString()</td>
                    <td>@item.Activity.PointValue</td>
                    <td>
                        @Html.ActionLink("Edit", "Edit", new { userId = item.UserId, activityId = item.ActivityId, date = item.Date })
                        |
                        @Html.ActionLink("Delete", "Delete", new { userId = item.UserId, activityId = item.ActivityId, date = item.Date.ToShortDateString() })
                    </td>
                </tr>
            }

        </table>
    </div>
    <div class="tab-pane active" id="calendar-view2">
        <div id="calendar"></div>
    </div>   
    <div id='loading' style='display: none'>loading...</div>
    <div class="modal hide fade" id="add-activity">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
            <h3>Enter Activity</h3>
        </div>
        <div class="modal-body">
            @{ Html.RenderAction("CreatePartial", "UserActivity", new { username = ViewBag.Username }); }
            
        </div>
        <div class="modal-footer">
            <a href="#" class="btn" data-dismiss="modal">Close</a>
            <a href="#" class="btn btn-primary" data-dismiss="modal" onclick="saveActivity()">Save changes</a>
        </div>
    </div>

</div>

@section scripts
{
    <script type="text/javascript">

        var calendar;

        $(function ()
        {
            var date = new Date();
            var d = date.getDate();
            var m = date.getMonth();
            var y = date.getFullYear();

            calendar = $('#calendar').fullCalendar({
                header: {
                    left: 'prev,next today',
                    center: 'title',
                    right: 'month'
                },
                selectable: true,
                selectHelper: true,
                select: function (start, end, allDay)
                {
                    $('#UserActivity_Date').val($.fullCalendar.formatDate(start, 'MM/dd/yyyy'));
                    $('#add-activity').modal("show")
                },
                editable: true,
                events: "@Url.Action("GetUserActivity", "UserActivity", new { username = ViewBag.Username })"
            });            
        });

        function saveActivity()
        {
            var form = $("#create_activity_form");
            if (form.valid())
            {
                $.post(form.attr("action"), form.serialize(), function (response)
                {
                    if (response.Success == true)
                    {
                        calendar.fullCalendar('renderEvent',
                            {
                                title: response.Title,
                                start: response.Date,
                                end: response.Date,
                                allDay: true
                            },
                            true // make the event "stick"
                        );
                        calendar.fullCalendar('unselect');
                    }
                });
            }
        }

    </script>
}

ExternalBadass/ExternalBadass/Views/UserActivity/Status.cshtml
@model ExternalBadass.ViewModels.CurrentStatusViewModel

@{
    ViewBag.Title = "Status";
}

@section menu
{
  
    <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Users
            <span class="caret"></span>
        </a>
        <ul class="dropdown-menu" role="menu">
            @foreach(var user in Model.Users.Where(u => u.UserId != Model.Incentives.First().UserId))
            {
                <li role="presentation">@Html.ActionLink(user.Username, "status", "useractivity", new{username=user.Username}, new {role="menuitem" })</li>
            }
        </ul>
    </li>  
}

<section id="current-incentive-progress">

    <div class="chart-container">
        
        @foreach (var breakdown in Model.IncentiveBreakdowns.OrderBy(i => i.Incentive.Deadline))
        {
            <div class="chart">
                <h3 class="center-text">@breakdown.Incentive.Description</h3>
                <h4 class="center-text">@breakdown.Incentive.StartDate.ToShortDateString() - @breakdown.Incentive.Deadline.ToShortDateString()</h4>
                <div id="incentive_@(breakdown.Incentive.IncentiveId)"></div>
            </div>
        }
    </div>
</section>

@section Scripts {

    <script type="text/javascript">


        var w = 320,                       // width and height, natch
            h = 320,
            r = Math.min(w, h) / 2,        // arc radius
            dur = 750,                     // duration, in milliseconds
            color = d3.scale.category10(),
            donut = d3.layout.pie().sort(null),
            arc = d3.svg.arc().innerRadius(r - 70).outerRadius(r - 20);

        // ---------------------------------------------------------------------

        @foreach (var breakdown in @Model.IncentiveBreakdowns)
        {
            <text>
        var id = "@breakdown.Incentive.IncentiveId";
        var centerLabel = '@(Math.Round(breakdown.Incentive.PercentComplete * 100, 0))' + '%'

        var labels = [];
        var percentArray = [];

            @foreach (var activity in breakdown.ActivityTotals)
            {
                @: labels.push('@(activity.Name)');
                        @: percentArray.push(@activity.PointTotal);
            }

        var data = { label: '@breakdown.Incentive.Description', pct: percentArray }
        addDonut(id, centerLabel, labels, data);
            </text>
        }

        function addDonut(id, centerLabel, activeLabels, activeData) {
            var svg = d3.select("#incentive_" + id).append("svg:svg")
                .attr("width", w).attr("height", h);

            var arc_grp = svg.append("svg:g")
                .attr("class", "arcGrp")
                .attr("transform", "translate(" + (w / 2) + "," + (h / 2) + ")");

            var label_group = svg.append("svg:g")
                .attr("class", "lblGroup")
                .attr("transform", "translate(" + (w / 2) + "," + (h / 2) + ")");

            // GROUP FOR CENTER TEXT
            var center_group = svg.append("svg:g")
                .attr("class", "ctrGroup")
                .attr("transform", "translate(" + (w / 2) + "," + (h / 2) + ")");

            // CENTER LABEL
            var pieLabel = center_group.append("svg:text")
                .attr("dy", ".7em").attr("class", "chartLabel")
                .attr("text-anchor", "middle")
                .text(centerLabel);

            // DRAW ARC PATHS
            var arcs = arc_grp.selectAll("path")
                .data(donut(data.pct));
            arcs.enter().append("svg:path")
                .attr("stroke", "white")
                .attr("stroke-width", 0.5)
                .attr("fill", function (d, i) { return color(i); })
                .attr("d", arc)
                .each(function (d) { this._current = d });

            // DRAW SLICE LABELS
            var sliceLabel = label_group.selectAll("text")
                .data(donut(data.pct));
            sliceLabel.enter().append("svg:text")
                .attr("class", "arcLabel")
                .attr("transform", function (d) { return "translate(" + arc.centroid(d) + ")"; })
                .attr("text-anchor", "middle")
                .text(function (d, i) { return activeLabels[i]; });


            arcs.data(donut(activeData.pct)); // recompute angles, rebind data
            arcs.transition().ease("elastic").duration(dur).attrTween("d", arcTween);

            sliceLabel.data(donut(activeData.pct));
            sliceLabel.transition().ease("elastic").duration(dur)
                .attr("transform", function (d) { return "translate(" + arc.centroid(d) + ")"; })
                .style("fill-opacity", function (d) { return d.value == 0 ? 1e-6 : 1; });

            pieLabel.text(centerLabel);
        }

        // --------- "PAY NO ATTENTION TO THE MAN BEHIND THE CURTAIN" ---------

        // Store the currently-displayed angles in this._current.
        // Then, interpolate from this._current to the new angles.
        function arcTween(a) {
            var i = d3.interpolate(this._current, a);
            this._current = i(0);
            return function (t) {
                return arc(i(t));
            };
        }


    </script>
}

ExternalBadass/ExternalBadass/Views/UserActivity/_Create.cshtml
@model ExternalBadass.ViewModels.UserActivityViewModel


@using (Html.BeginForm("AddActivity", "UserActivity", FormMethod.Post, new { @id = "create_activity_form" }))
{
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>UserActivity</legend>

            @Html.Hidden("UserActivity.User.Username", Model.CurrentUser.Username)

         <div class="editor-label">
            @Html.LabelFor(model => model.CurrentUser.Username)
        </div>
        <div class="editor-field">
            @Html.DropDownList("UserActivity.User.UserId", Model.UserSelectList)
        </div>
         <div class="editor-label">
            <label for="UserActivity.ActivityId">Date</label>
        </div>
        <div class="editor-field">
            @Html.TextBox("UserActivity.Date", DateTime.Now.ToShortDateString())
        </div>
         <div class="editor-label">
            <label for="UserActivity.ActivityId">Activity</label>
        </div>
        <div class="editor-field">
            @Html.DropDownList("UserActivity.Activity.ActivityId", Model.ActivitySelectList)
        </div>
    </fieldset>
}